# Site settings
title: Hoai An Blog
header-img: img/home-bg.jpg
email: hoaianr@rubysg.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://hoaianr.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
