# Site settings
title: Hoai An Blog
header-img: img/home-bg.jpg
email: hoaianr@rubysg.com
description: "Personal blog for sharing what I'm doing now!"
baseurl: ""
url: "http://hoaianr.github.io"

twitter_username: SBootstrap
github_username:  hoaianr
facebook_username:  hoaian_uit

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
