# Site settings
title: Hoai An's Blog
header-img: img/home-bg.jpg
email: jackyinvn@gmail.com
description: "Share what I loving and doing"
baseurl: ""
url: "http://hoaianr.github.io"

twitter_username: SBootstrap
github_username:  hoaianr
facebook_username:  hoaian_uit

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
