# Site settings
title: MIC International Labs
header-img: /img/home-bg.jpg
email: jackyinvn@gmail.com
description: "Share what I'm loving and doing"
baseurl: ""
url: "https://www.miclabs.co"

twitter_username: hoaianr
github_username:  hoaianr
facebook_username:  hoaian_uit

gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]